# Generated by Django 6.0.3 on 2026-03-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_blog_sys_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catugory',
            new_name='Category',
        ),
    ]
